kind: Deployment
apiVersion: apps/v1
metadata:
  name: lembretes-deployment
spec:
  replicas: 1
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: lembretes
  template:
    metadata:
      labels:
        app: lembretes
        version: v01
    spec:
      containers:
      - name: lembretes
        image: vitordio/lembretes